# Generated by Django 5.2 on 2026-09-26 19:02

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Two-letter USPS code, stored uppercase.', max_length=2)),
                ('search_key', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_state_name_alive', violation_error_message='A state with this name already exists.'), models.UniqueConstraint(django.db.models.functions.text.Upper('code'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_state_code_alive', violation_error_message='A state with this code already exists.')],
            },
        ),
    ]
