# Generated by Django 5.2 on 2026-09-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_agencynote_agencystatelicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencystatelicense',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('pending', 'Pending'), ('applied', 'Applied'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('jit', 'JIT')], default='active', max_length=10),
        ),
    ]
