# Generated by Django 5.2 on 2026-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('womens', 'Womens'), ('mens', 'Mens'), ('maternity', 'Maternity'), ('accessories', 'Accessories'), ('holidays', 'Holidays')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('polos', 'Polos'), ('quarter-zips', 'Quarter Zips'), ('shirts', 'Shirts'), ('pants', 'Pants'), ('belts', 'Belts'), ('hats', 'Hats'), ('backpacks', 'Backpacks')], max_length=20),
        ),
    ]
