# Generated by Django 5.2 on 2026-09-11 00:38

import apps.users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Used to sign in. Stored lowercased.', max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('login_type', models.CharField(choices=[('local', 'Local password'), ('sso', 'Single sign-on')], default='local', max_length=16, verbose_name='login type')),
                ('is_active', models.BooleanField(default=True, help_text='Unset instead of deleting an account, to keep its history.', verbose_name='active')),
                ('is_blocked', models.BooleanField(default=False, help_text='Set by an administrator to deny sign-in without deactivating.', verbose_name='blocked')),
                ('must_change_password', models.BooleanField(default=False, help_text='Force a password reset on the next successful sign-in.', verbose_name='must change password')),
                ('is_staff', models.BooleanField(default=False, help_text='Can sign in to the Django admin site.', verbose_name='staff status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['full_name', 'email'],
            },
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
