# Generated by Django 5.2 on 2026-09-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Stamped into every JWT issued for this account. Bumping it makes all outstanding tokens - access included - stop validating.', verbose_name='token version'),
        ),
    ]
