# Generated by Django 5.2 on 2026-09-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstatelicense',
            name='health',
            field=models.BooleanField(default=False, help_text='The licence covers health insurance.'),
        ),
        migrations.AddField(
            model_name='agentstatelicense',
            name='life',
            field=models.BooleanField(default=False, help_text='The licence covers life insurance.'),
        ),
    ]
