# Generated by Django 5.2 on 2026-09-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentstatelicense_life_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='ssn_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='SSN (last 4)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
