# Generated by Django 5.2 on 2026-09-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_login_code_plain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='login_code',
        ),
    ]
