# Generated by Django 5.2 on 2026-09-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storefront.product'),
        ),
        migrations.AlterField(
            model_name='request',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
