# Generated by Django 5.2 on 2026-09-27 23:08

import apps.base.storage
import apps.policies.models.certifications
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, storage=apps.base.storage.PrivateStorage(), upload_to=apps.policies.models.certifications.certification_file_path),
        ),
        migrations.AddField(
            model_name='certification',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
