# Generated by Django 5.2 on 2026-10-07 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_certifications_by_carrier_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierpolicy',
            name='policy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_policies', to='policies.policytype'),
        ),
    ]
