# Generated by Django 5.2 on 2026-09-30 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_agencystatelicense_status'),
        ('agents', '0006_remove_agent_login_code'),
        ('carriers', '0006_carrier_state_licenses'),
        ('passwords', '0003_password_link_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='agency.agency'),
        ),
        migrations.AlterField(
            model_name='password',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to='agents.agent'),
        ),
        migrations.AddConstraint(
            model_name='password',
            constraint=models.UniqueConstraint(condition=models.Q(('agency__isnull', False), ('deleted_at__isnull', True)), fields=('agency', 'carrier'), name='uniq_password_agency_carrier_alive', violation_error_message='The agency already has a password at this carrier.'),
        ),
        migrations.AddConstraint(
            model_name='password',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agency__isnull', True), ('agent__isnull', False)), models.Q(('agency__isnull', False), ('agent__isnull', True)), _connector='OR'), name='password_agent_or_agency', violation_error_message='A password belongs to an agent or the agency.'),
        ),
    ]
