# Generated by Django 5.2 on 2026-09-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
