# Generated by Django 5.2 on 2026-09-30 21:37

from django.db import migrations, models


def status_from_is_active(apps, schema_editor):
    # Every carrier starts "active"; the ones that were switched off become "inactive".
    Carrier = apps.get_model('carriers', 'Carrier')
    Carrier._base_manager.filter(is_active=False).update(status='inactive')


def is_active_from_status(apps, schema_editor):
    Carrier = apps.get_model('carriers', 'Carrier')
    Carrier._base_manager.update(is_active=False)
    Carrier._base_manager.filter(status='active').update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0002_carrier_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('applied', 'Applied'), ('pending', 'Pending'), ('expired', 'Expired'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=10),
        ),
        migrations.RunPython(status_from_is_active, is_active_from_status),
    ]
