# Generated by Django 5.2 on 2026-09-30 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def rows_from_available_states(apps, schema_editor):
    # One active row per state a carrier already had; number, dates and lines are left blank.
    Carrier = apps.get_model('carriers', 'Carrier')
    CarrierStateLicense = apps.get_model('carriers', 'CarrierStateLicense')
    CarrierStateLicense.objects.bulk_create(
        CarrierStateLicense(carrier=carrier, state=state, status='active')
        for carrier in Carrier._base_manager.prefetch_related('available_states')
        for state in carrier.available_states.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_agencystatelicense_status'),
        ('carriers', '0005_rename_supp_ancillary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierStateLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('pending', 'Pending'), ('applied', 'Applied'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('jit', 'JIT')], default='active', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('life', models.BooleanField(default=False, help_text='Covers life insurance in this state.')),
                ('health', models.BooleanField(default=False, help_text='Covers health insurance in this state.')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='carriers.carrier')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrier_licenses', to='agency.state')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('carrier', 'state'), name='uniq_carrier_state_license_alive', violation_error_message='This carrier already has this state.')],
            },
        ),
        # The rows are dropped with the table on the way back; available_states is untouched.
        migrations.RunPython(rows_from_available_states, migrations.RunPython.noop),
    ]
